# Generated by Django 4.2.6 on 2023-10-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people_and_groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
